### ISSUE TITLE
VCF format for genome browser

### ISSUE THREAD

**Issue by husamia** [kcleal/dysgu#4]
Is the VCF output compatible with genome browser? I am getting error that the reference allele is missing when I try to open the VCF output with IGV. This would be highly needed for visualize the results.

**Comment by kcleal** [comment]
Hi, thanks for pointing this out. This is caused by the reference base being labelled with a "." 
Whilst this issue is resolved, you can use awk to replace the "." with an "N" base; this will allow you to load the results in IGV:
`awk 'OFS="\t" {if (/^#/) {print} else {$4 = "N"; print}}' input.vcf > output.vcf`

**Comment by husamia** [comment]
> Hi, thanks for pointing this out. This is caused by the reference base being labelled with a "."
> Whilst this issue is resolved, you can use awk to replace the "." with an "N" base; this will allow you to load the results in IGV:
> `awk 'OFS="\t" {if (/^#/) {print} else {$4 = "N"; print}}' input.vcf > output.vcf`

Now I can visualize the results in IGV that's very good. I want to save the output on the screen to a file. is there a way to do that?

**Comment by kcleal** [comment]
In IGV you can try File --> Save Image. Alternatively, print screen

**Comment by husamia** [comment]
Sorry. I didn't clearly state the question. I know how to take image from IGV. I was asking about the text output in the terminal.

**Comment by husamia** [comment]
Thanks for your help. My questions were answered.
